# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "baf6c9cee6ec6d1d64f15a820241b49f"
name = "Fitwell Admin"
application_url = "https://admin.fitwellbuckle.co"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_locations,read_marketing_events,read_markets,read_orders,read_products,read_script_tags,read_themes,write_draft_orders,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"
